name: Build and Deploy to DEV (CloudHub 2.0)

on:
  workflow_dispatch:

env:
  ENVIRONMENT: DEV
  TARGET: Cloudhub-EU-Central-1
  BUSINESS_GROUP: gruppo-florence
  MULE_RUNTIME_VERSION: 4.9
  REPLICAS: "1"
  VCORES: "0.1"
  APPLICATION_NAME: gf-testpushgit-dev
  MAVEN_SETTINGS_PATH: ~/.m2/settings.xml

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Prepare Maven settings.xml
      run: |
        mkdir -p ~/.m2
        cp settings.xml $MAVEN_SETTINGS_PATH
        sed -i 's|ANYPOINT_CLIENT_ID|${{ secrets.ANYPOINT_CLIENT_ID }}|g' $MAVEN_SETTINGS_PATH
        sed -i 's|ANYPOINT_CLIENT_SECRET|${{ secrets.ANYPOINT_CLIENT_SECRET }}|g' $MAVEN_SETTINGS_PATH

    - name: Build and Deploy to Exchange
      run: mvn clean deploy --settings $MAVEN_SETTINGS_PATH -DskipTests

  deploy-cloudhub:
    needs: build-and-publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Prepare Maven settings.xml
      run: |
        mkdir -p ~/.m2
        cp settings.xml $MAVEN_SETTINGS_PATH
        sed -i 's|ANYPOINT_CLIENT_ID|${{ secrets.ANYPOINT_CLIENT_ID }}|g' $MAVEN_SETTINGS_PATH
        sed -i 's|ANYPOINT_CLIENT_SECRET|${{ secrets.ANYPOINT_CLIENT_SECRET }}|g' $MAVEN_SETTINGS_PATH

    - name: Deploy to CloudHub 2.0
      run: |
        mvn deploy -DmuleDeploy \
          --settings $MAVEN_SETTINGS_PATH \
          -DapplicationName=$APPLICATION_NAME \
          -Dtarget=$TARGET \
          -Denv=$ENVIRONMENT \
          -DbusinessGroup=$BUSINESS_GROUP \
          -DmuleRuntime=$MULE_RUNTIME_VERSION \
          -Dreplicas=$REPLICAS \
          -DvCores=$VCORES \
          -DskipTests
